export default {
  BORDER_RADIUS_SMALL: 5,
  BORDER_RADIUS_MEDIUM: 15,
  BORDER_RADIUS_LARGE: 25,
  BORDER_RADIUS_ROUND: 1000,
  BORDER_WIDTH_SMALL: 0.5,
  BORDER_WIDTH_MEDIUM: 1,
  BORDER_WIDTH_LARGE: 2,
  BORDER_MARGIN_VERTICAL: 15,
  BORDER_MARGIN_HORIZONTAL: 15,
  BORDER_PADDING_VERTICAL: 10,
  BORDER_PADDING_HORIZONTAL: 15,
}
